### ISSUE TITLE
Undefined errors (with using DUB)

### ISSUE THREAD

**Issue by joelcnz** [azihassan/youtube-d#47]
```
Joel-Computer:youtube-d-0.0.4 joelchristensen$ dub build -b release
    Starting Performing "release" build using /Library/D/dmd/bin/dmd for x86_64.
    Building duktape 0.4.0: building configuration [library]
../../../../.dub/packages/duktape/0.4.0/duktape/source/duk_config.d(909,25): Error: undefined identifier `jmp_buf`
../../../../.dub/packages/duktape/0.4.0/duktape/source/duk_config.d(910,20): Error: undefined identifier `setjmp`
Error /Library/D/dmd/bin/dmd failed with exit code 1.
```

I'm on macOS.

**Comment by azihassan** [comment]
Thanks for the report. I haven't texted it on MacOS but I just pushed a commit to test that on GitHub since I don't have access to a macbook

**Comment by azihassan** [comment]
I looked into it, and it turned out that one of the libraries failed to build under MacOS. Just merged [a patch](https://github.com/azihassan/youtube-d/pull/48) and it seems to be working now, at least on [Github actions](https://github.com/azihassan/youtube-d/actions/runs/7414456735/job/20175566589?pr=48). Could you pull from main and try again?

**Comment by joelcnz** [comment]
I get the same errors. I tried the shell files, but didn't anywhere - command not found (used sudo on them).

**Comment by azihassan** [comment]
Oh ok, I guess there's a mismatch in `sed` between your version of MacOS and whichever one is used in GitHub actions.

In that case I would have to merge the fix into duktaped and wait for it to be deployed in code.dlang.org, or fork it and find a way to reference it in dub.json. I'll try implementing the second approach tomorrow but if all else fails, we could always resort to Docker.

**Comment by joelcnz** [comment]
This is a trick I do with my libraries (notice the '../'s):

```
	"importPaths": [
		"source",
		"source/io",
		"../JMiscLib/source",
	],
	"sourcePaths": [
		"source",
		"source/io",
		"../JMiscLib/source",
	]
```

**Comment by azihassan** [comment]
TIL, thanks. I also found out dub supports [local dependencies](https://docs.webfreak.org/dub-reference/build_settings/). But I couldn't get either of these two solutions to work unless I include duktaped's source code in the project, which I'm trying to avoid. In the end, I decided to fork duktaped and put the changes [there](https://github.com/azihassan/duktaped), this way I can maintain both projects separately. [This PR](https://github.com/azihassan/youtube-d/pull/49) includes that change. Just merged it into main, let me know if it's still causing you trouble.

**Comment by joelcnz** [comment]
I still get the same errors. I used ```"duktaped": "*" -> 1.0.0```

**Comment by azihassan** [comment]
Hmm not sure what else it could be honestly. Maybe dub still references the previous duktaped version instead of the fork. Make sure dub.selections.json both point to the fork, and delete `../../../../.dub/packages/duktape` (or whichever folder holds the dub dependencies) to force a redownload and run `dub clean`, then `dub build --force` for good measure.

**Comment by joelcnz** [comment]
I've wiped duktape packages off, used clean and force flags - but I'm still getting the same errors.

```../../../../.dub/packages/duktaped/1.0.0/duktaped/source/etc/c/duk_config.d(907,25): Error: undefined identifier `jmp_buf`
../../../../.dub/packages/duktaped/1.0.0/duktaped/source/etc/c/duk_config.d(908,20): Error: undefined identifier `setjmp`
Error /Library/D/dmd/bin/dmd failed with exit code 1.```

**Comment by azihassan** [comment]
I'm confused why it says 1.0.0

I don't think dub's targeting the right version, my fork doesn't have anything in line 908: https://github.com/azihassan/duktaped/blob/c1f1939c8e62fbb4022050a0b3b1ba2164881067/source/duk_config.d#L908

What's inside your dub.json and dub.selections.json?

**Comment by joelcnz** [comment]
dub.json:
```
{
	"authors": [
		"Hassan Azi"
	],
	"copyright": "Copyright © 2023, Hassan Azi",
	"dependencies": {
		"htmld": "~>0.3.7",
		"duktaped": "*"
	},
	"description": "Youtube downloader",
	"license": "MIT",
	"name": "youtube-d"
}
```

dub.selections.json:
```
{
	"fileVersion": 1,
	"versions": {
		"duktaped": "1.0.0",
		"htmld": "0.3.7"
	}
}
```

**Comment by azihassan** [comment]
It looks different from the ones in the main branch, try pulling from main since it includes the MacOS compatible version of duktaped

**Comment by joelcnz** [comment]
I don't understand how to pull from the main branch?

**Comment by azihassan** [comment]
Not sure how your project copy is set up, but the easiest way would be to `git clone` the project in another directory to automatically get the latest changes.

**Comment by joelcnz** [comment]
I don't understand how to pull from the main branch?

**Comment by azihassan** [comment]
I'm not sure I follow, did the previous suggestion not work ?

**Comment by joelcnz** [comment]
I mean to look later. (I guess git clone (copied git link) would pull from the main).

**Comment by joelcnz** [comment]
I'm not getting those errors any more. I recloned it.
